Support building with GHC 9.2
`base-4.16.*` adds an `Ior` newtype to `Data.Bits` to represent bitwise
inclusive OR. This clashes with the `Ior` data constructor used in
`Language.JVM.Parser`, however:

```
[3 of 4] Compiling Language.JVM.Parser ( src/Language/JVM/Parser.hs, interpreted )

src/Language/JVM/Parser.hs:601:20: error:
    Ambiguous occurrence ‘Ior’
    It could refer to
       either ‘Data.Bits.Ior’,
              imported from ‘Data.Bits’ at src/Language/JVM/Parser.hs:123:1-16
           or ‘Language.JVM.Common.Ior’,
              imported from ‘Language.JVM.Common’ at src/Language/JVM/Parser.hs:135:1-26
              (and originally defined at src/Language/JVM/Common.hs:310:5-7)
    |
601 |     0x80 -> return Ior
    |                    ^^^
```

Thankfully, the fix is simple: use an explicit import from `Data.Bits` to only
import the `Bits` class and nothing else.